CREATE TABLE "bitebytesRecipes" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"image" text,
	"title" text,
	"readyInMinutes" real,
	"servings" real,
	"sourceUrl" text,
	"vegetarian" boolean,
	"vegan" boolean,
	"glutenFree" boolean,
	"dairyFree" boolean,
	"veryHealthy" boolean,
	"cheap" boolean,
	"veryPopular" boolean,
	"sustainable" boolean,
	"lowFodmap" boolean,
	"weightWatcherSmartPoints" integer,
	"gaps" text,
	"preparationMinutes" text,
	"cookingMinutes" text,
	"aggregateLikes" integer,
	"healthScore" real,
	"creditsText" text,
	"license" text,
	"sourceName" text,
	"pricePerServing" text,
	"extendedIngredients" jsonb[],
	"summary" text,
	"cuisines" jsonb[],
	"dishTypes" jsonb[],
	"diets" jsonb[],
	"occasions" jsonb[],
	"winePairing" jsonb,
	"instructions" text,
	"analyzedInstructions" jsonb[],
	"originalId" text,
	"spoonacularScore" double precision,
	"spoonacularSourceUrl" text,
	"imageType" text,
	"language" text,
	CONSTRAINT "bitebytesRecipes_title_key" UNIQUE("title")
);
--> statement-breakpoint
CREATE TABLE "bitebytesUser" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "bitebytesuser_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" text NOT NULL,
	"password" text,
	"username" text,
	"image" text DEFAULT '/user.png',
	CONSTRAINT "bitebytesUser_pkey" PRIMARY KEY("id","email"),
	CONSTRAINT "bitebytesUser_id_key" UNIQUE("id")
);
--> statement-breakpoint
CREATE TABLE "countries" (
	"id" bigint NOT NULL,
	"countryCode" text NOT NULL,
	"countryName" text,
	CONSTRAINT "countries_pkey" PRIMARY KEY("id","countryCode")
);
--> statement-breakpoint
ALTER TABLE "countries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "extendedIngredients" (
	"id" bigint NOT NULL,
	"recipeId" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"aisle" text,
	"image" text,
	"consistency" text,
	"name" text,
	"nameClean" text,
	"original" text,
	"originalName" text,
	"amount" double precision,
	"unit" text,
	"meta" text[],
	"measures" jsonb,
	"uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "extendedIngredients_uniqueId_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	CONSTRAINT "extendedIngredients_uniqueId_key" UNIQUE("uniqueId")
);
--> statement-breakpoint
CREATE TABLE "likedRecipes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "likedRecipes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"userId" bigint,
	"recipeId" bigint NOT NULL,
	CONSTRAINT "unique_userid_recipeid2" UNIQUE("userId","recipeId")
);
--> statement-breakpoint
CREATE TABLE "mealPlanning" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "MealPlanning_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"title" text,
	"recipeId" bigint,
	"userId" bigint,
	"mealType" text NOT NULL,
	"date" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "requiredIngredients" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "RequirededIngredint_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"userId" bigint,
	"uniqueIngredientId" bigint,
	"recipeId" bigint,
	"requiredDate" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "savedRecipes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "savedRecipes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"userId" bigint,
	"quantity" bigint,
	"recipeId" bigint NOT NULL,
	CONSTRAINT "unique_userid_recipeid" UNIQUE("userId","recipeId")
);
--> statement-breakpoint
CREATE TABLE "userIngredientList" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customIngredients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"userId" bigint,
	"name" text,
	"amount" double precision,
	"unit" text,
	"image" text,
	"isPurchased" boolean DEFAULT false,
	"consistency" text
);
--> statement-breakpoint
ALTER TABLE "extendedIngredients" ADD CONSTRAINT "extendedIngredients_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "public"."bitebytesRecipes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "likedRecipes" ADD CONSTRAINT "likedRecipes_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "public"."bitebytesRecipes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "likedRecipes" ADD CONSTRAINT "likedRecipes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."bitebytesUser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mealPlanning" ADD CONSTRAINT "MealPlanning_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "public"."bitebytesRecipes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mealPlanning" ADD CONSTRAINT "MealPlanning_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."bitebytesUser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "requiredIngredients" ADD CONSTRAINT "RequirededIngredint_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "public"."bitebytesRecipes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "requiredIngredients" ADD CONSTRAINT "RequirededIngredint_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."bitebytesUser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "requiredIngredients" ADD CONSTRAINT "requiredIngredients_uniqueIngredientId_fkey" FOREIGN KEY ("uniqueIngredientId") REFERENCES "public"."extendedIngredients"("uniqueId") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "savedRecipes" ADD CONSTRAINT "savedRecipes_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "public"."bitebytesRecipes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "savedRecipes" ADD CONSTRAINT "savedRecipes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."bitebytesUser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "userIngredientList" ADD CONSTRAINT "customIngredients_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."bitebytesUser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "countries" AS PERMISSIVE FOR SELECT TO public USING (true);